### ISSUE TITLE
Reports API

### ISSUE THREAD

**Issue by DonDejvo** [Webler-Group/webler-codes#20]
## TODO

- [x] - Create new controller in backend controllers.

Add following routes (check guide on wiki):

- [x]  _reports/reportUser_ - Create report with status of OPENED and authorId of logged user.
- **Role**: USER
- **Body**
   - reason: `ReportReason`
   - message: `string?`
   - type: `ReportType`
   - reportedUserId: `BigInt`

- [ ] _reports/getReports_ - Returns list of filtered and ordered reports. 
- **Role**: MODERATOR
- **Body**
   - status: `ReportStatus?`
   - reportedUserId: `BigInt?`
   - asssigneeId: `BigInt?`
   - orderBy: `string` - name of column
   - page: `number` - page count
   - count: `number` - number of records on page

- [ ] _reports/getReports_ - Returns info about reports filtered and ordered based on paraeters. Only returns parent reports.
- **Role**: MODERATOR
- **Body**
   - status: `ReportStatus[]?`
   - reportedUserId: `BigInt?`
   - asssigneeId: `BigInt?`
   - orderBy: `string` - name of column
   - page: `number` - page count
   - count: `number` - number of records on page

- [x] _reports/setParent_ - Set parent report for selected reports.
- **Role**: MODERATOR
- **Body**
   - reportIds: `Bigint[]`
   - parentId: `BigInt`

- [x] _reports/getReport_ - Returns report info.
- **Role**: MODERATOR
- **Body**
   - reportId: `BigInt`

- [x] _reports/closeReport_ - Updates report and may create and associate bans. If the report has child reports, their status is updated as well.
- **Role**: MODERATOR
- **Body**
   - reportId: `BigInt`
   - note: `string?`
   - bans: `{ userId: BigInt; durationInDays: number; reason: ReportReason; note: string?; }[]`

- [x] _reports/banUser_ - Bans user.
- **Role**: MODERATOR
- **Body**
   - userId: `BigInt`
   - durationInDays: `number`
   - reason: `ReportReason`

- [x] - Create router and assign all functions from controller.

**Comment by Mehran7kl** [comment]
`reportedUserId` shall not be optional in `createReport` request since it is not optional in `Report` model.

**Comment by DonDejvo** [comment]
> `reportedUserId` shall not be optional in `createReport` request since it is not optional in `Report` model. 

Actually there was a reason for it, it is multipurpose report endpoint to report user profiles, posts, ... but as you mentioned it I got another better idea.

Rename the endpoint to _reports/reportUser_ and make the reportedUserId required then later when we add e.g. post we add also new report endpoint.

**Comment by Mehran7kl** [comment]
I think the ``banUser` endpoint is used by moderators to ban a user immediately. so what should be ban reason of that user?

**Comment by DonDejvo** [comment]
> I think the ``banUser` endpoint is used by moderators to ban a user immediately. so what should be ban reason of that user?

Yes, quick ban when mod see someone doing bad stuff, the reason comes from ReportReason enum, it is chosen by the moderator.

**Comment by Mehran7kl** [comment]
> > I think the ``banUser` endpoint is used by moderators to ban a user immediately. so what should be ban reason of that user?
> 
> Yes, quick ban when mod see someone doing bad stuff, the reason comes from ReportReason enum, it is chosen by the moderator.

The `banUser` request body lacks the `reason` property.

**Comment by DonDejvo** [comment]
> > > I think the `banUser` endpoint is used by moderators to ban a user immediately. so what should be ban reason of that user?
> > 
> > 
> > Yes, quick ban when mod see someone doing bad stuff, the reason comes from ReportReason enum, it is chosen by the moderator.
> 
> The `banUser` request body lacks the `reason` property.

I am sorry, my bad. Added in the description.
