### ISSUE TITLE
backend code api

### ISSUE THREAD

**Issue by paul-caron** [Webler-Group/webler-codes#24]
## TODO

- [ ] - Create new controller in backend controllers.

Add following routes (check guide on wiki):

- [ ]  _code/getSource_ - Get source code from database. 
- **Role**: USER
- **Body**
   - codeId: `bigint`
   - accessToken: `string?` (no token is fine if code is public)
- **Response**
   - title: `string`
   - language: `string`
   - source: `string`

- [ ]  _code/delete_ - Delete code from database. 
- **Role**: USER
- **Body**
   - codeId: `bigint`
   - accessToken: `string`
- **Response**
   - success:  `bool`
 
- [ ]  _code/save_ - Save/Edit code into database. 
- **Role**: USER
- **Body**
   - title: `string`
   - language: `string`
   - source: `string`
   - accessToken: `string`
   - codeId: `bigint` (optional for new save, or save as. needed for editing)
- **Response**
   - success:  `bool`

- [ ]  _code/getTemplate_ - Get a template of code to start a coding project. 
- **Role**: USER
- **Body**
   - language: `string`
- **Response**
   - template:  `string`

- [ ] - Create router and assign all functions from controller.
