### ISSUE TITLE
Use js number for bigint representation

### ISSUE THREAD

**Issue by DonDejvo** [Webler-Group/webler-codes#28]
**TODO**

- [ ] update zod schema
- [ ] remove BigInt() wrappers
- [ ] wrap with Number() on response
