### ISSUE TITLE
Integrating Code Evaluation

### ISSUE THREAD

**Issue by DonDejvo** [Webler-Group/webler-codes#44]
### TODO

- [ ] Add redis container and utilize redis queue (bull library).
- [ ] Add docker in docker.
   - Pull images from github registry.
   - Run images via node child process.
- [ ] Add CodeEvalTask table.
- [ ] Extend Code Controller.
   - _createEvalTask_ - Add job in redis queue which run required docker image to evaluate code. Create task to db and returns id.
   Body
   ```
   { codeId, stdin }
   ```
   Response
   ```
   { taskId }
   ```
   - _getEvalTask_ - Get task by id.
   Body
   ```
   { taskId }
   ```
